[project]
name = "blackjack-simulator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pygame-cards>=0.1.3",
    "pygame>=2.6.1",
    "pip>=25.0.1",
    "jupyter>=1.1.1",
    "loguru>=0.7.3",
]
